apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: ghcr.io/emilk92/cpp-prog-docker:latest
    argocd-image-updater.argoproj.io/cpp-image.update-strategy: latest
  name: cpp-prog-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/emilk92/cpp-prog-argocd
    path: cpp-prog
    kustomize:
      namespace: default
      namePrefix: kustomize-
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5

