apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/emilk92/cpp-prog-docker:1.1.6
    argocd-image-updater.argoproj.io/write-back-method: argocd
  name: cpp-prog
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      path: cpp-prog
      repoURL: https://github.com/emilk92/cpp-prog-argocd
      targetRevision: HEAD

